sonar.projectKey=LeangOC_OC2P7-FSJA
sonar.organization=leangoc

sonar.host.url=https://sonarcloud.io

# Sources
sonar.sources=back/src/main,front/src

# Tests
sonar.tests=back/src/test

# Java binaries
sonar.java.binaries=back/build/classes

# Encodage
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml
sonar.coverage.exclusions=**/*Application.java,**/dto/**,**/controller/FrontendLogController.java