name: Continuous Integration / Continuous Deployment

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-test-sonar:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      ####################################################
      # Java
      ####################################################

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      ####################################################
      # Backend
      ####################################################

      - name: Build backend
        working-directory: back
        run: chmod +x gradlew && ./gradlew clean build

      ####################################################
      # Node
      ####################################################

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      ####################################################
      # Frontend
      ####################################################

      - name: Install frontend dependencies
        working-directory: front
        run: npm ci

      - name: Build frontend
        working-directory: front
        run: npm run build

      - name: Run Angular tests
        working-directory: front
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage

      ####################################################
      # SonarCloud
      ####################################################
      # Désactivé temporairement :
      # Incident SonarCloud (HTTP 504 sur /analysis/jres)
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ########################################################
  # Continuous Deployment
  ########################################################

  docker-publish:

    name: Publish Docker Images

    needs: build-test-sonar

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      ####################################################
      # Docker Buildx
      ####################################################

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      ####################################################
      # Login Docker Hub
      ####################################################

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ####################################################
      # Backend Image
      ####################################################

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/microcrm-back:latest
      ####################################################
      # Frontend Image
      ####################################################

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/microcrm-front:latest